// Builds src/ai/navigator/vocabulary.ts — the words the typo normaliser may
// correct TO — from the simulator question bank (the bank of the 106 000-run
// test) and the navigator's example bank. Run after changing either:
//   npx tsx apps/mobile/test/sim/buildVocabulary.ts
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { fold } from "../../src/ai/copilotBrain";
import { EXAMPLES } from "../../src/ai/navigator/examples";
import { SIM_CATEGORIES } from "./questionBank";

const words = new Set<string>();
const add = (text: string) => { for (const w of fold(text).split(" ")) if (w.length >= 4 && !/\d/.test(w)) words.add(w); };
for (const c of SIM_CATEGORIES) for (const [b] of c.bases) add(b);
for (const list of Object.values(EXAMPLES)) for (const e of list ?? []) add(e);
const sorted = [...words].sort();
writeFileSync(join(__dirname, "..", "..", "src", "ai", "navigator", "vocabulary.ts"), [
  "// GENERATED by test/sim/buildVocabulary.ts from the simulator question bank",
  "// and the example bank — the words the typo normaliser may correct to.",
  "// Folded (fold()): lower case, і/ї/и → и, є/е → е, no apostrophes.",
  `export const VOCABULARY: readonly string[] = ${JSON.stringify(sorted)};`,
  "",
].join("\n"));
console.log(`vocabulary: ${sorted.length} words`);
