// DemoEngine — spec section 26 ("DEMO MODE") + section 27 ("TEST ROUTE").
//
// "Demo mode must be real software test harness, not fake UI... Every
// simulation must feed the same production engines. Do NOT make a separate
// fake UI engine." Every simulate* method here only flips a condition on the
// synthetic GNSS/IMU sample stream that tick() then runs through the actual
// production modules — GNSSMonitor, SensorFusionEngine, RouteProgressEngine,
// OffRouteDetector, NavigationStateMachine, LandmarkEngine, AIEngine,
// DemoVisionProvider. Nothing here computes a NavigationState field
// directly; it all comes out of those real engines.
//
// "Create reproducible demo route: Kyiv center -> Kyiv Oblast destination.
// Use actual route generated by routing engine... Do not invent a route
// geometry just for UI." start() calls DemoRoutingProvider.route() for a
// real Dijkstra-computed route; nothing here hand-draws a path.

import type { LatLon, NavigationState, GNSSIntegrityState, ConfidenceBand } from "./types";
import type { GNSSRawSample } from "./gnss-monitor";
import { GNSSMonitor } from "./gnss-monitor";
import { deadReckon } from "./dead-reckoning";
import { calculateConfidence } from "./confidence";
import { initialBearing } from "./geodesy";
import { SensorFusionEngine } from "./sensor-fusion";
import type { Route } from "./route-engine";
import { RouteProgressEngine, distanceFromRouteCorridorM, positionAtDistance } from "./route-engine";
import { DemoRoutingProvider, type DemoRoadGraph } from "./demo-routing-provider";
import { OffRouteDetector } from "./off-route-detector";
import { NavigationStateMachine } from "./navigation-state-machine";
import { LandmarkEngine, type POI, type LandmarkQueryResult } from "./landmark-engine";
import { AIEngine, DeterministicDemoAIProvider, type NavigationContext } from "./ai-engine";
import { DemoVisionProvider, type VisionDetection } from "./vision-provider";
import { TelemetryLogger } from "./telemetry-logger";
import { AirAlertLayer, DemoAirAlertProvider } from "./air-alert-layer";

const AVERAGE_SPEED_MPS = 11;
const GNSS_CONFIG = { maxPlausibleSpeedMps: 35, maxJumpM: 120, maxFreshAgeMs: 6000, accuracyGoodM: 10, accuracyBadM: 80 };

export type DemoEngineOptions = {
  graph: DemoRoadGraph;
  origin: LatLon;
  destination: LatLon;
  pois?: POI[];
};

export class DemoEngine {
  private routingProvider: DemoRoutingProvider;
  private progressEngine = new RouteProgressEngine();
  private gnssMonitor = new GNSSMonitor(GNSS_CONFIG);
  private fusion = new SensorFusionEngine();
  private offRouteDetector = new OffRouteDetector();
  private stateMachine = new NavigationStateMachine();
  private landmarkEngine = new LandmarkEngine();
  private aiProvider = new DeterministicDemoAIProvider();
  // Generous cap: a long simulated drive (e.g. Kyiv -> Boryspil at 1 tick/s)
  // can log several thousand GNSS_FIX events; keep enough history that an
  // early GNSS_LOST/RECOVERY isn't evicted before a report is pulled.
  private telemetry = new TelemetryLogger(20_000);
  private airAlert = new AirAlertLayer(new DemoAirAlertProvider());
  private visionProvider: DemoVisionProvider;

  private route: Route | null = null;
  private simTimeMs = 0;
  private distanceTraveledM = 0;
  private lastGnssRawSample: GNSSRawSample | null = null;
  private lastTrustedPosition: NavigationState["trustedPosition"] = null;
  private lastFusedPosition: LatLon | null = null;
  private lastHeadingDeg = 0;
  private currentState: NavigationState;

  // Synthetic-condition toggles the simulate* controls flip; tick() is the
  // only place that reads them, and only to build the next synthetic sample.
  private gnssDegraded = false;
  private gnssLost = false;
  private pendingGpsJump = false;
  private pendingWrongHeading = false;
  private forcedOffRoute = false;
  private networkAvailable = true;

  constructor(private options: DemoEngineOptions) {
    this.routingProvider = new DemoRoutingProvider(options.graph);
    this.visionProvider = new DemoVisionProvider(options.pois ?? []);
    this.currentState = idleState();
  }

  getState(): NavigationState {
    return this.currentState;
  }
  getRoute(): Route | null {
    return this.route;
  }
  getTelemetry(): TelemetryLogger {
    return this.telemetry;
  }

  /** Section 27: a real routed trip, Kyiv center -> Kyiv Oblast destination. */
  async start(): Promise<void> {
    this.route = await this.routingProvider.route({ origin: this.options.origin, destination: this.options.destination });
    this.telemetry.log("ROUTE_UPDATE", { distanceM: this.route.distanceM }, this.simTimeMs);
    this.stateMachine.tick(baseSmInput({ routeRequested: true }));
    this.stateMachine.tick(baseSmInput({ routeReady: true }));
    this.distanceTraveledM = 0;
    this.lastTrustedPosition = null;
    this.lastFusedPosition = this.options.origin;
    this.currentState = this.buildState("IDLE-TO-ACTIVE");
  }

  reset(): void {
    this.simTimeMs = 0;
    this.distanceTraveledM = 0;
    this.lastGnssRawSample = null;
    this.lastTrustedPosition = null;
    this.lastFusedPosition = null;
    this.gnssDegraded = this.gnssLost = this.pendingGpsJump = this.pendingWrongHeading = this.forcedOffRoute = false;
    this.networkAvailable = true;
    this.route = null;
    this.gnssMonitor = new GNSSMonitor(GNSS_CONFIG);
    this.offRouteDetector = new OffRouteDetector();
    this.stateMachine = new NavigationStateMachine();
    this.telemetry.clear();
    this.currentState = idleState();
  }

  // --- section 26's control list ---
  simulateGnssDegradation(): void { this.gnssDegraded = true; this.gnssLost = false; }
  simulateGnssLoss(): void { this.gnssLost = true; this.gnssDegraded = false; }
  restoreGnss(): void { this.gnssLost = false; this.gnssDegraded = false; }
  simulateGpsJump(): void { this.pendingGpsJump = true; }
  simulateWrongHeading(): void { this.pendingWrongHeading = true; }
  simulateOffRoute(): void { this.forcedOffRoute = true; }
  clearOffRoute(): void { this.forcedOffRoute = false; }
  simulateNetworkLoss(): void { this.networkAvailable = false; }
  restoreNetwork(): void { this.networkAvailable = true; }

  simulateLandmark(pois: POI[], queryText: string): LandmarkQueryResult {
    if (!this.route || !this.lastFusedPosition) {
      return { kind: "no_match", message: "Маршрут ще не активний." };
    }
    return this.landmarkEngine.identifyLandmarkQuery(pois, queryText, this.route, this.lastFusedPosition, AVERAGE_SPEED_MPS);
  }

  async simulateCameraDetection(): Promise<VisionDetection[]> {
    if (!this.lastFusedPosition) return [];
    return this.visionProvider.analyzeFrame(
      { timestamp: this.simTimeMs, width: 640, height: 480 },
      { position: this.lastFusedPosition, headingDeg: this.lastHeadingDeg }
    );
  }

  async askAI(userText: string): Promise<string> {
    const ctx = this.buildAIContext();
    return this.aiProvider.answer(ctx, userText);
  }

  /** Advance the simulation by `dtSeconds`, running every production engine. */
  tick(dtSeconds: number): NavigationState {
    if (!this.route) throw new Error("DemoEngine.tick: call start() first");
    this.simTimeMs += dtSeconds * 1000;

    // Ground truth: the ONE thing DemoEngine invents, by design — a
    // simulated vehicle position advancing along the real routed geometry
    // (or off it, if simulateOffRoute() is active). Everything downstream
    // treats this the way real sensors would: through GNSSMonitor/fusion.
    if (!this.forcedOffRoute) {
      this.distanceTraveledM = Math.min(this.route.distanceM, this.distanceTraveledM + AVERAGE_SPEED_MPS * dtSeconds);
    }
    const onRoutePosition = positionAtDistance(this.route.geometry, this.distanceTraveledM);
    const groundTruth = this.forcedOffRoute ? offsetPosition(onRoutePosition, 80) : onRoutePosition;
    this.lastHeadingDeg = this.lastFusedPosition ? initialBearing(this.lastFusedPosition, groundTruth) : 0;

    // Build this tick's synthetic GNSS sample (or none, if GNSS is lost).
    let gnssSample: GNSSRawSample | null = null;
    if (!this.gnssLost) {
      let lat = groundTruth.lat, lon = groundTruth.lon;
      if (this.pendingGpsJump) { lat += 0.003; this.pendingGpsJump = false; } // ~330m implausible jump
      let headingDeg = this.lastHeadingDeg;
      if (this.pendingWrongHeading) { headingDeg = (headingDeg + 150) % 360; this.pendingWrongHeading = false; }
      gnssSample = {
        lat, lon, timestamp: this.simTimeMs,
        accuracyM: this.gnssDegraded ? 60 : 5,
        speedMps: AVERAGE_SPEED_MPS,
        headingDeg,
      };
    }

    const integrity = gnssSample ? this.gnssMonitor.evaluate(this.lastGnssRawSample, gnssSample, this.simTimeMs) : null;
    if (gnssSample) this.lastGnssRawSample = gnssSample;

    const gnssIntegrityState: GNSSIntegrityState = !gnssSample ? "LOST" : integrity!.trusted ? "NORMAL" : "DEGRADED";

    // Dead reckoning from the last trusted fix (or last fused position if none yet).
    const drAnchor = this.lastTrustedPosition?.position ?? this.lastFusedPosition ?? groundTruth;
    const drPosition = deadReckon({ position: drAnchor, speedMps: AVERAGE_SPEED_MPS, headingDeg: this.lastHeadingDeg, dtSeconds });

    const gnssQuality = integrity ? 1 - integrity.anomalyScore : 0;
    const fused = this.fusion.fuse({
      gnss: gnssSample && integrity
        ? { position: { lat: gnssSample.lat, lon: gnssSample.lon }, speedMps: gnssSample.speedMps, headingDeg: gnssSample.headingDeg, timestamp: gnssSample.timestamp, quality: gnssQuality }
        : null,
      deadReckoned: { position: drPosition, speedMps: AVERAGE_SPEED_MPS, headingDeg: this.lastHeadingDeg },
    });
    this.lastFusedPosition = fused.position;

    const freshness = integrity ? integrity.freshnessScore : 0;
    const confidence = calculateConfidence({
      gnssQuality, freshness,
      sensorAgreement: 0.85,
      mapMatchQuality: gnssIntegrityState === "LOST" ? 0.4 : 0.85,
      routeConsistency: this.forcedOffRoute ? 0.2 : 0.9,
    });

    if (integrity?.trusted) {
      this.lastTrustedPosition = {
        position: { ...fused.position, timestamp: this.simTimeMs, accuracyM: gnssSample!.accuracyM, source: "GNSS" },
        confidence: confidence.value, band: confidence.band, source: "GNSS",
      };
      this.telemetry.log("GNSS_FIX", { accuracyM: gnssSample!.accuracyM }, this.simTimeMs);
    }
    if (gnssIntegrityState === "DEGRADED") this.telemetry.log("GNSS_DEGRADED", {}, this.simTimeMs);
    if (gnssIntegrityState === "LOST") this.telemetry.log("GNSS_LOST", {}, this.simTimeMs);

    const progress = this.progressEngine.computeProgress(this.route, fused.position, fused.speedMps);
    const distanceOffRouteM = distanceFromRouteCorridorM(this.route, fused.position);
    const offRouteConfirmed = this.offRouteDetector.update({
      distanceFromRouteM: distanceOffRouteM, roadMismatch: false, headingMismatchDeg: null, timestamp: this.simTimeMs,
    });
    if (offRouteConfirmed) this.telemetry.log("OFF_ROUTE", { distanceOffRouteM }, this.simTimeMs);

    const hasArrived = progress.distanceRemainingM < 10;

    const mode = this.stateMachine.tick({
      gnssIntegrity: gnssIntegrityState,
      confidenceBand: confidence.band,
      offRouteConfirmed,
      hasArrived,
      routeRequested: false,
      routeReady: !offRouteConfirmed, // once off-route clears (real reroute would set this), allow return to ACTIVE
    });
    if (mode === "RECOVERING") this.telemetry.log("RECOVERY", {}, this.simTimeMs);

    this.currentState = {
      mode,
      position: { position: { ...fused.position, timestamp: this.simTimeMs, accuracyM: gnssSample?.accuracyM ?? null, source: fused.source === "GNSS" ? "GNSS" : fused.source === "DEAD_RECKONING" ? "DEAD_RECKONING" : "FUSED" }, confidence: confidence.value, band: confidence.band, source: fused.source === "GNSS" ? "GNSS" : fused.source === "DEAD_RECKONING" ? "DEAD_RECKONING" : "FUSED" },
      trustedPosition: this.lastTrustedPosition,
      gnss: gnssIntegrityState,
      confidence: confidence.value,
      confidenceBand: confidence.band,
      speedMps: fused.speedMps,
      headingDeg: fused.headingDeg,
      routeProgressM: progress.distanceCompletedM,
      routeRemainingM: progress.distanceRemainingM,
      nextStep: progress.nextStep,
      nearbyLandmarks: [],
      offRoute: offRouteConfirmed,
      networkAvailable: this.networkAvailable,
      offlineMapAvailable: false,
      lastTrustedFixAt: this.lastTrustedPosition?.position.timestamp ?? null,
      updatedAt: this.simTimeMs,
    };
    return this.currentState;
  }

  private buildState(_label: string): NavigationState {
    return {
      mode: this.stateMachine.getMode(),
      position: null,
      trustedPosition: null,
      gnss: "NORMAL",
      confidence: 0, confidenceBand: "UNKNOWN",
      speedMps: null, headingDeg: null,
      routeProgressM: 0, routeRemainingM: this.route?.distanceM ?? 0,
      nextStep: this.route?.steps[0] ?? null,
      nearbyLandmarks: [], offRoute: false,
      networkAvailable: this.networkAvailable, offlineMapAvailable: false,
      lastTrustedFixAt: null, updatedAt: this.simTimeMs,
    };
  }

  private buildAIContext(): NavigationContext {
    return {
      state: this.currentState,
      route: this.route,
      nearbyLandmarks: [],
      nearbyPOI: this.options.pois ?? [],
      recentEvents: [...this.telemetry.getEvents()],
    };
  }
}

function idleState(): NavigationState {
  return {
    mode: "IDLE", position: null, trustedPosition: null, gnss: "NORMAL",
    confidence: 0, confidenceBand: "UNKNOWN", speedMps: null, headingDeg: null,
    routeProgressM: 0, routeRemainingM: 0, nextStep: null, nearbyLandmarks: [],
    offRoute: false, networkAvailable: true, offlineMapAvailable: false,
    lastTrustedFixAt: null, updatedAt: 0,
  };
}

function baseSmInput(overrides: Partial<{
  gnssIntegrity: GNSSIntegrityState; confidenceBand: ConfidenceBand; offRouteConfirmed: boolean;
  hasArrived: boolean; routeRequested: boolean; routeReady: boolean;
}>) {
  return {
    gnssIntegrity: "NORMAL" as GNSSIntegrityState, confidenceBand: "HIGH" as ConfidenceBand,
    offRouteConfirmed: false, hasArrived: false, routeRequested: false, routeReady: false,
    ...overrides,
  };
}

function offsetPosition(p: LatLon, meters: number): LatLon {
  return { lat: p.lat + meters / 111_320, lon: p.lon };
}
