// The spec's question bank (Shturman spec, Appendix A): 20 categories × 5 base
// phrasings, each asked in 7 speaking styles in 7 system situations = 4,900
// rows, exactly as in the document. For every base phrasing: the intents
// that answer it correctly and the snapshot field the answer rests on.
import type { NavigatorIntent } from "../../src/ai/navigator/intents";

export const BANK_A: [category: string, question: string, field: string, intents: NavigatorIntent[]][] = [
  ["Статус GPS і позиції", "Який зараз сигнал?", "gnssState / positionConfidence", ["gpsStatus", "signalLost"]],
  ["Статус GPS і позиції", "Наскільки ти впевнений у моїй позиції?", "gnssState / positionConfidence", ["confidence"]],
  ["Статус GPS і позиції", "Ти взагалі знаєш де я?", "gnssState / positionConfidence", ["confidence", "whereAmI"]],
  ["Статус GPS і позиції", "Чому карта смикається?", "gnssState / positionConfidence", ["gpsStatus"]],
  ["Статус GPS і позиції", "Що з точністю позиції?", "gnssState / positionConfidence", ["gpsStatus", "confidence"]],
  ["Втрата/деградація сигналу", "Пропав сигнал, що робити?", "gnssState / gnssLastFixAgeMs", ["signalLost"]],
  ["Втрата/деградація сигналу", "А якщо сигнал зовсім пропаде надовго?", "gnssState / gnssLastFixAgeMs", ["signalLost"]],
  ["Втрата/деградація сигналу", "Сигнал поганий але ще є", "gnssState / gnssLastFixAgeMs", ["gpsStatus", "signalLost"]],
  ["Втрата/деградація сигналу", "Скільки вже немає сигналу?", "gnssState / gnssLastFixAgeMs", ["signalLost", "gpsStatus"]],
  ["Втрата/деградація сигналу", "Коли сигнал повернеться?", "gnssState / gnssLastFixAgeMs", ["signalLost", "gpsStatus"]],
  ["Маршрут і рух", "Куди далі?", "nextManeuver / routeRemainingM / etaTimestamp", ["routeNext"]],
  ["Маршрут і рух", "Далеко ще?", "nextManeuver / routeRemainingM / etaTimestamp", ["eta"]],
  ["Маршрут і рух", "Скільки км лишилось?", "nextManeuver / routeRemainingM / etaTimestamp", ["eta"]],
  ["Маршрут і рух", "Коли приїду?", "nextManeuver / routeRemainingM / etaTimestamp", ["eta"]],
  ["Маршрут і рух", "Чому ти мене туди ведеш?", "nextManeuver / routeRemainingM / etaTimestamp", ["routeWhy"]],
  ["Наступний маневр", "Через скільки поворот?", "nextManeuver", ["routeNext"]],
  ["Наступний маневр", "Скоро повертати?", "nextManeuver", ["routeNext"]],
  ["Наступний маневр", "Куди повертати далі?", "nextManeuver", ["routeNext"]],
  ["Наступний маневр", "На яку вулицю зараз?", "nextManeuver", ["routeNext"]],
  ["Наступний маневр", "Це той поворот праворуч?", "nextManeuver", ["routeNext", "onRoute"]],
  ["Відхилення від маршруту", "Я збився з маршруту?", "offRoute / reroutingInProgress", ["reroute", "onRoute"]],
  ["Відхилення від маршруту", "Я на правильній дорозі?", "offRoute / reroutingInProgress", ["onRoute", "reroute"]],
  ["Відхилення від маршруту", "Що як я поїду в об’їзд?", "offRoute / reroutingInProgress", ["reroute", "routeWhy"]],
  ["Відхилення від маршруту", "Ти перебудовуєш маршрут?", "offRoute / reroutingInProgress", ["reroute"]],
  ["Відхилення від маршруту", "Чому маршрут змінився?", "offRoute / reroutingInProgress", ["routeWhy", "reroute"]],
  ["Безпека і тривога", "Тривога, що робити?", "alarmStatus / nearbyShelters", ["alert", "shelter"]],
  ["Безпека і тривога", "Де найближче укриття?", "alarmStatus / nearbyShelters", ["shelter"]],
  ["Безпека і тривога", "Це точно найближче укриття?", "alarmStatus / nearbyShelters", ["shelterWhy"]],
  ["Безпека і тривога", "Тривога вже закінчилась?", "alarmStatus / nearbyShelters", ["alert"]],
  ["Безпека і тривога", "Скільки метрів до укриття?", "alarmStatus / nearbyShelters", ["shelter"]],
  ["Пункти незламності", "Де найближчий пункт незламності?", "nearbyShelters (category=resilience_point)", ["place"]],
  ["Пункти незламності", "Далеко до пункту незламності?", "nearbyShelters (category=resilience_point)", ["place"]],
  ["Пункти незламності", "Там є зарядка для телефону?", "nearbyShelters (category=resilience_point)", ["place"]],
  ["Пункти незламності", "Пункт незламності зараз працює?", "nearbyShelters (category=resilience_point)", ["place"]],
  ["Пункти незламності", "Скільки йти пішки до пункту незламності?", "nearbyShelters (category=resilience_point)", ["place"]],
  ["Локація", "Де я зараз?", "currentLat / currentLon / positionSource", ["whereAmI"]],
  ["Локація", "Яка це вулиця?", "currentLat / currentLon / positionSource", ["whereAmI"]],
  ["Локація", "Який це район?", "currentLat / currentLon / positionSource", ["whereAmI"]],
  ["Локація", "Далеко я від центру?", "currentLat / currentLon / positionSource", ["whereAmI", "noData"]],
  ["Локація", "Покажи де я на карті", "currentLat / currentLon / positionSource", ["whereAmI"]],
  ["Мета-питання про штурмана", "Чому ти так відповів?", "lastNavaResponse / snapshot history", ["explain"]],
  ["Мета-питання про штурмана", "Ти можеш помилятися?", "lastNavaResponse / snapshot history", ["explain", "confidence"]],
  ["Мета-питання про штурмана", "Повтори", "lastNavaResponse / snapshot history", ["repeat"]],
  ["Мета-питання про штурмана", "Звідки ти це знаєш?", "lastNavaResponse / snapshot history", ["explain"]],
  ["Мета-питання про штурмана", "Ти реально розумієш що я питаю?", "lastNavaResponse / snapshot history", ["explain", "smalltalk"]],
  ["Питання без даних (чесна відмова)", "Яка зараз пробка на дорозі?", "немає відповідного поля — обов’язкова чесна відмова", ["noData"]],
  ["Питання без даних (чесна відмова)", "Яка погода попереду?", "немає відповідного поля — обов’язкова чесна відмова", ["noData"]],
  ["Питання без даних (чесна відмова)", "Що там за аварія попереду?", "немає відповідного поля — обов’язкова чесна відмова", ["noData"]],
  ["Питання без даних (чесна відмова)", "Скільки коштує бензин по дорозі?", "немає відповідного поля — обов’язкова чесна відмова", ["noData"]],
  ["Питання без даних (чесна відмова)", "Чи працює міст попереду?", "немає відповідного поля — обов’язкова чесна відмова", ["noData"]],
  ["Офлайн режим", "Немає інтернету, що тепер?", "networkOnline / offlinePackageAvailable", ["offline"]],
  ["Офлайн режим", "Карта працює офлайн?", "networkOnline / offlinePackageAvailable", ["offline"]],
  ["Офлайн режим", "Укриття видно без мережі?", "networkOnline / offlinePackageAvailable", ["offline"]],
  ["Офлайн режим", "Офлайн пакет взагалі завантажений?", "networkOnline / offlinePackageAvailable", ["offline"]],
  ["Офлайн режим", "Що працює без зв’язку?", "networkOnline / offlinePackageAvailable", ["offline"]],
  ["Емоційні та кризові звернення", "Мені страшно, що робити", "весь Context Snapshot + тон відповіді ≤3 речення", ["emotion"]],
  ["Емоційні та кризові звернення", "Я не знаю що робити", "весь Context Snapshot + тон відповіді ≤3 речення", ["emotion"]],
  ["Емоційні та кризові звернення", "Допоможи мені будь ласка", "весь Context Snapshot + тон відповіді ≤3 речення", ["emotion"]],
  ["Емоційні та кризові звернення", "Я розгубився", "весь Context Snapshot + тон відповіді ≤3 речення", ["emotion"]],
  ["Емоційні та кризові звернення", "Заспокой мене і скажи що робити", "весь Context Snapshot + тон відповіді ≤3 речення", ["emotion"]],
  ["Роздратування користувача", "Ти взагалі корисний?", "тон відповіді — коротко, по суті, без виправдань", ["frustration"]],
  ["Роздратування користувача", "Чому ти такий тупий", "тон відповіді — коротко, по суті, без виправдань", ["frustration"]],
  ["Роздратування користувача", "Ти нічого не вмієш", "тон відповіді — коротко, по суті, без виправдань", ["frustration"]],
  ["Роздратування користувача", "Це ж елементарне питання", "тон відповіді — коротко, по суті, без виправдань", ["frustration"]],
  ["Роздратування користувача", "Навіщо ти взагалі потрібен", "тон відповіді — коротко, по суті, без виправдань", ["frustration"]],
  ["Погодні та зовнішні умови (без даних)", "Дощ буде по дорозі?", "немає джерела — чесна відмова з поясненням", ["noData"]],
  ["Погодні та зовнішні умови (без даних)", "Ожеледиця попереду є?", "немає джерела — чесна відмова з поясненням", ["noData"]],
  ["Погодні та зовнішні умови (без даних)", "Видимість нормальна там?", "немає джерела — чесна відмова з поясненням", ["noData"]],
  ["Погодні та зовнішні умови (без даних)", "Вітер сильний зараз?", "немає джерела — чесна відмова з поясненням", ["noData"]],
  ["Погодні та зовнішні умови (без даних)", "Туман попереду буде?", "немає джерела — чесна відмова з поясненням", ["noData"]],
  ["Планування маршруту", "Є коротший шлях?", "routeActive / alternative routing", ["routeWhy"]],
  ["Планування маршруту", "А через об’їзну швидше?", "routeActive / alternative routing", ["routeWhy"]],
  ["Планування маршруту", "Можна без платної дороги?", "routeActive / alternative routing", ["routeWhy"]],
  ["Планування маршруту", "Покажи альтернативний маршрут", "routeActive / alternative routing", ["routeWhy", "reroute"]],
  ["Планування маршруту", "Цей маршрут найкращий?", "routeActive / alternative routing", ["routeWhy"]],
  ["Швидкість і час", "З якою я зараз швидкістю їду?", "speedMps / etaTimestamp", ["speed"]],
  ["Швидкість і час", "Я перевищую швидкість?", "speedMps / etaTimestamp", ["speed"]],
  ["Швидкість і час", "Коли я приїду якщо їхати так само?", "speedMps / etaTimestamp", ["eta"]],
  ["Швидкість і час", "Скільки часу в дорозі?", "speedMps / etaTimestamp", ["eta"]],
  ["Швидкість і час", "Я встигну до комендантської?", "speedMps / etaTimestamp", ["noData", "eta"]],
  ["Стан пристрою і мережі", "Я зараз в демо режимі чи реальному?", "networkOnline / isDemoMode", ["dataSource"]],
  ["Стан пристрою і мережі", "Інтернет є зараз?", "networkOnline / isDemoMode", ["offline"]],
  ["Стан пристрою і мережі", "Дані актуальні чи застарілі?", "networkOnline / isDemoMode", ["dataSource"]],
  ["Стан пристрою і мережі", "Ти зараз онлайн?", "networkOnline / isDemoMode", ["offline"]],
  ["Стан пристрою і мережі", "Це реальні дані чи демо?", "networkOnline / isDemoMode", ["dataSource"]],
  ["Повторні та уточнюючі питання", "Що ти сказав?", "lastNavaResponse", ["repeat"]],
  ["Повторні та уточнюючі питання", "Ще раз будь ласка", "lastNavaResponse", ["repeat"]],
  ["Повторні та уточнюючі питання", "Не почув, повтори", "lastNavaResponse", ["repeat"]],
  ["Повторні та уточнюючі питання", "Що це значить?", "lastNavaResponse", ["explain"]],
  ["Повторні та уточнюючі питання", "Поясни детальніше", "lastNavaResponse", ["explain"]],
  ["Загальний статус поїздки", "Як в цілому справи з поїздкою?", "весь Context Snapshot (зведений статус)", ["status"]],
  ["Загальний статус поїздки", "Все нормально?", "весь Context Snapshot (зведений статус)", ["status"]],
  ["Загальний статус поїздки", "Розкажи загальний статус", "весь Context Snapshot (зведений статус)", ["status"]],
  ["Загальний статус поїздки", "Щось критичне є зараз?", "весь Context Snapshot (зведений статус)", ["status", "alert"]],
  ["Загальний статус поїздки", "Все під контролем?", "весь Context Snapshot (зведений статус)", ["status"]],
  ["Голосові транскрипти з шумом (симуляція помилок розпізнавання)", "скока ще пилити", "нормалізація тексту перед класифікацією", ["eta"]],
  ["Голосові транскрипти з шумом (симуляція помилок розпізнавання)", "де укрит тя", "нормалізація тексту перед класифікацією", ["shelter"]],
  ["Голосові транскрипти з шумом (симуляція помилок розпізнавання)", "шо там з сигна лом", "нормалізація тексту перед класифікацією", ["gpsStatus", "signalLost"]],
  ["Голосові транскрипти з шумом (симуляція помилок розпізнавання)", "куд далі ", "нормалізація тексту перед класифікацією", ["routeNext"]],
  ["Голосові транскрипти з шумом (симуляція помилок розпізнавання)", "тревога шо роб", "нормалізація тексту перед класифікацією", ["alert", "shelter"]],
];

/** The 7 speaking styles of the bank (the same generation as the document). */
export function bankStyles(q: string): string[] {
  const lower = q.charAt(0).toLowerCase() + q.slice(1);
  return [q, `слухай, ${lower}`, `а скажи будь ласка, ${lower}`, q.endsWith("?") ? `${q.slice(0, -1)} взагалі?` : `${q} взагалі?`, `мені терміново треба знати: ${lower}`, `${q} Скажи чесно.`, `вибач що питаю, але ${lower}`];
}

/** The bank's 7 situations → the scenarios of test/support/navigatorScenarios.ts. */
export const BANK_SITUATIONS: [name: string, key: string][] = [
  ["Норма", "normal"], ["Деградація сигналу", "degraded"], ["Втрата сигналу", "lost"], ["Відновлення сигналу", "recovered"],
  ["Тривога", "alert"], ["Відхилення від маршруту", "offroute"], ["Звичайний рух", "driving"],
];
